"""v1.9 voyage templates.

Each template is a pure function that returns an
**editable ``Mission``** seeded with a sensible starting set
of waypoints. Templates are not locked presets — the artist
is expected to rename / reorder / tweak after creation.

Five templates:

* ``solar_system_tour`` — the inner-to-outer planets, drawn
  from the v0.4 JPL Horizons fetch convention.
* ``nearest_stars_tour`` — Sun + closest neighbours; a
  "stand on the doorstep" cinematic.
* ``redshift_tour`` — increasing-z extragalactic anchors
  showing the Hubble flow.
* ``empty_voyage`` — no waypoints, just the title /
  description / tags scaffold.
* ``selected_objects_tour`` — driven by an iterable of UIDs
  the dialog hands in (e.g. the user's current bookmark
  selection or a search result list).

Templates are pure-Python; no Cinema 4D, no DB, no network.
The dialog wires them up behind a "New Mission From
Template" picker.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Iterable, List, Optional, Tuple

from .mission import Mission, MissionWaypoint


# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------


@dataclass
class TemplateDescriptor:
    """One entry in the template picker. The dialog renders
    ``label`` + ``description``; clicking the row invokes
    ``builder(**kwargs)`` to produce a fresh Mission."""

    name: str
    label: str
    description: str
    builder: Callable[..., Mission]


# ---------------------------------------------------------------------------
# Solar System tour
# ---------------------------------------------------------------------------


#: The inner + outer planets in the canonical UNAV JPL
#: Horizons format (``jpl:<body>:<epoch_iso>`` UIDs). Epoch
#: is the v0.4 / v1.2 default of J2026-01-01 — the artist
#: can edit it post-creation. The values are intentionally
#: strings (not enums) so the connector can match the body
#: tokens it accepts.
SOLAR_SYSTEM_BODIES: Tuple[str, ...] = (
    "Mercury", "Venus", "Earth", "Mars",
    "Jupiter", "Saturn", "Uranus", "Neptune",
)

#: Default epoch ISO string used by the bundled solar-system
#: template. JD 2461041.5 == 2026-01-01T00:00:00.
DEFAULT_TEMPLATE_EPOCH_ISO: str = "2026-01-01T00:00:00"
DEFAULT_TEMPLATE_EPOCH_JD: float = 2461041.5


def solar_system_tour(
    *,
    epoch_iso: str = DEFAULT_TEMPLATE_EPOCH_ISO,
    epoch_jd: float = DEFAULT_TEMPLATE_EPOCH_JD,
    duration_seconds: float = 4.0,
) -> Mission:
    """Eight planet-stop fly-through. UIDs follow the v0.4
    Horizons convention; the dialog can re-resolve them via
    the active dataset registry."""
    waypoints: List[MissionWaypoint] = []
    for body in SOLAR_SYSTEM_BODIES:
        waypoints.append(MissionWaypoint(
            kind="orbital",
            uid=f"jpl:{body}:{epoch_iso}",
            label=body,
            catalog_source="JPL Horizons",
            object_type="planet",
            epoch_jd=float(epoch_jd),
            duration_seconds=float(duration_seconds),
            tags=["solar-system", "planet", "template"],
        ))
    return Mission(
        title="Solar System Tour",
        description=(
            "Inner-to-outer planet sweep at "
            f"{epoch_iso}. Generated by the v1.9 voyage "
            "template system. Edit freely."
        ),
        tags=["template", "solar-system"],
        waypoints=waypoints,
    )


# ---------------------------------------------------------------------------
# Nearest stars tour
# ---------------------------------------------------------------------------


#: Common-name labels + Gaia DR3 source IDs for the closest
#: stars. The IDs may not all resolve in every dataset
#: (depending on what the artist has imported); the dialog
#: warns when a uid doesn't resolve at playback time.
#: Distances are ICRS Cartesian parsec used as cached
#: positions so the path renders even without a metadata
#: lookup.
NEAREST_STARS: Tuple[Tuple[str, str, Tuple[float, float, float]], ...] = (
    ("Proxima Centauri", "gaia:5853498713160606720", (-0.94, -0.79, -0.68)),
    ("Alpha Centauri A",  "gaia:5853498713190520576", (-0.95, -0.80, -0.68)),
    ("Barnard's Star",    "gaia:4472832130942575872", ( 0.01,  1.82, +0.30)),
    ("Wolf 359",          "gaia:3864972938605115520", (-1.92, -1.10, +0.86)),
    ("Lalande 21185",     "gaia:4034171629095945472", (-0.84,  2.42, +0.99)),
    ("Sirius A",          "gaia:2947050466531873024", (-0.45, -1.62, -2.07)),
)


def nearest_stars_tour(
    *,
    duration_seconds: float = 4.0,
) -> Mission:
    """Six closest-stars fly-through with cached parsec
    positions so the path renders even without an active
    metadata lookup."""
    waypoints: List[MissionWaypoint] = [MissionWaypoint(
        kind="coordinate",
        label="Sun (origin)",
        x_c4d=0.0, y_c4d=0.0, z_c4d=0.0,
        x_pc=0.0, y_pc=0.0, z_pc=0.0,
        duration_seconds=float(duration_seconds),
        tags=["star", "template", "nearby"],
        notes="Solar System origin — start of the local-space tour.",
    )]
    for label, uid, (x, y, z) in NEAREST_STARS:
        waypoints.append(MissionWaypoint(
            kind="object",
            uid=uid,
            label=label,
            catalog_source="Gaia DR3",
            object_type="star",
            x_c4d=float(x), y_c4d=float(y), z_c4d=float(z),
            x_pc=float(x), y_pc=float(y), z_pc=float(z),
            duration_seconds=float(duration_seconds),
            tags=["star", "template", "nearby"],
        ))
    return Mission(
        title="Nearest Stars Tour",
        description=(
            "Sun + nearest-neighbour stars. Cached parsec "
            "positions so the path renders without an active "
            "metadata lookup."
        ),
        tags=["template", "stars", "nearby"],
        waypoints=waypoints,
    )


# ---------------------------------------------------------------------------
# Redshift / extragalactic tour
# ---------------------------------------------------------------------------


#: A handful of extragalactic anchors at increasing redshift
#: drawn from SDSS/DESI conventions. Distances are computed
#: via the v0.5 redshift→Hubble proxy (treated as cached
#: parsec triples here so the path renders offline). Tags
#: include ``approximate`` because the proxy is coarse — see
#: REDSHIFT_DISTANCE_LIMITATIONS.md.
REDSHIFT_ANCHORS: Tuple[Tuple[str, str, str, float, float], ...] = (
    # (label, uid, kind, redshift_z, distance_pc)
    ("M31",                "named:M31",         "named",     0.000,        7.7e5),
    ("Virgo Cluster",      "named:Virgo",        "named",     0.0036,       1.6e7),
    ("3C273 (quasar)",     "sdss:3C273",         "object",    0.158,        7.1e8),
    ("Distant Galaxy",     "desi:distant-z1",    "object",    1.000,        4.5e9),
    ("High-z Quasar",      "desi:hiz-z3",        "object",    3.000,        1.3e10),
)


def redshift_tour(
    *, duration_seconds: float = 4.0,
) -> Mission:
    """Increasing-z extragalactic sweep. All distances are the
    v0.5 Hubble-law proxy; tagged ``approximate`` so the
    artist sees the caveat."""
    waypoints: List[MissionWaypoint] = []
    for label, uid, kind, z, dist_pc in REDSHIFT_ANCHORS:
        # ICRS-style position in pc → C4D world units (1 pc → 1 unit).
        waypoints.append(MissionWaypoint(
            kind=kind,
            uid=uid if kind != "named" else None,
            label=label,
            catalog_source="SDSS/DESI" if kind == "object" else None,
            object_type="galaxy" if "galaxy" in label.lower() else
                "quasar" if "quasar" in label.lower() else None,
            x_c4d=float(dist_pc), y_c4d=0.0, z_c4d=0.0,
            x_pc=float(dist_pc), y_pc=0.0, z_pc=0.0,
            duration_seconds=float(duration_seconds),
            tags=["template", "extragalactic", "approximate"],
            notes=(
                f"redshift z = {z:.4f}; distance is a Hubble-law "
                "proxy (see REDSHIFT_DISTANCE_LIMITATIONS.md)"
            ),
        ))
    return Mission(
        title="Redshift Tour",
        description=(
            "Increasing-z extragalactic anchors illustrating the "
            "Hubble flow. Distances are coarse Hubble-law proxies "
            "and not suitable for cosmology."
        ),
        tags=["template", "extragalactic", "approximate"],
        waypoints=waypoints,
    )


# ---------------------------------------------------------------------------
# Empty voyage
# ---------------------------------------------------------------------------


def empty_voyage(
    *,
    title: str = "New Voyage",
    description: str = "",
    tags: Optional[Iterable[str]] = None,
) -> Mission:
    """Zero-waypoint scaffold. Lets the dialog give the artist
    a fresh mission with a known title without pre-populating
    any stops."""
    return Mission(
        title=title or "New Voyage",
        description=description or "",
        tags=[str(t) for t in (tags or ["template"])],
    )


# ---------------------------------------------------------------------------
# Selected-objects tour
# ---------------------------------------------------------------------------


def selected_objects_tour(
    uids: Iterable[str],
    *,
    title: str = "Selected Objects Tour",
    duration_seconds: float = 4.0,
    catalog_source: Optional[str] = None,
) -> Mission:
    """Build a mission whose waypoints are the supplied UIDs in
    order. The dialog uses this when the artist has selected
    multiple bookmarks / search results and wants a quick
    fly-through."""
    waypoints: List[MissionWaypoint] = []
    for raw in uids:
        uid = (raw or "").strip()
        if not uid:
            continue
        waypoints.append(MissionWaypoint(
            kind="object",
            uid=uid,
            label=uid,
            catalog_source=catalog_source,
            duration_seconds=float(duration_seconds),
            tags=["template", "selected"],
        ))
    return Mission(
        title=title or "Selected Objects Tour",
        description=(
            f"Tour of {len(waypoints)} selected object(s). "
            "Generated by the v1.9 voyage template system."
        ),
        tags=["template", "selected"],
        waypoints=waypoints,
    )


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


TEMPLATE_REGISTRY: Tuple[TemplateDescriptor, ...] = (
    TemplateDescriptor(
        name="solar_system_tour",
        label="Solar System Tour",
        description="Mercury → Neptune at a default epoch.",
        builder=solar_system_tour,
    ),
    TemplateDescriptor(
        name="nearest_stars_tour",
        label="Nearest Stars Tour",
        description="Sun + the closest stellar neighbours.",
        builder=nearest_stars_tour,
    ),
    TemplateDescriptor(
        name="redshift_tour",
        label="Redshift / Extragalactic Tour",
        description="Increasing-z sweep illustrating the Hubble flow.",
        builder=redshift_tour,
    ),
    TemplateDescriptor(
        name="empty_voyage",
        label="Empty Voyage",
        description="Zero-waypoint scaffold; build everything yourself.",
        builder=empty_voyage,
    ),
    TemplateDescriptor(
        name="selected_objects_tour",
        label="Selected Objects Tour",
        description="Tour of UIDs you supply (e.g. selected bookmarks).",
        builder=selected_objects_tour,
    ),
)


def get_template(name: str) -> Optional[TemplateDescriptor]:
    """Look up a template by its stable ``name``. Returns
    ``None`` for unknown templates so the dialog can surface
    the failure cleanly."""
    if not name:
        return None
    target = name.strip().lower()
    for entry in TEMPLATE_REGISTRY:
        if entry.name == target:
            return entry
    return None


def list_templates() -> List[TemplateDescriptor]:
    """Return the registry as a list. Used by the dialog's
    template picker."""
    return list(TEMPLATE_REGISTRY)
