"""UNAV Pro v2.0 procedural authoring tools.

Pure-Python overlay computation + dataset-derived helpers.
See ``docs/V2_0_PROCEDURAL_AUTHORING_TOOLS.md`` for the
milestone overview.
"""

from __future__ import annotations

from .dataset_helpers import (
    DEFAULT_SHELL_REDSHIFTS,
    HUBBLE_KM_S_MPC,
    SPEED_OF_LIGHT_KM_S,
    BoundingSphere,
    DensityHeatmap,
    RedshiftShells,
    SourceDistribution,
    compute_bounding_sphere,
    compute_density_heatmap_placeholder,
    compute_redshift_shells_placeholder,
    compute_source_distribution,
)
from .overlays import (
    DEFAULT_OVERLAY_RADIUS_PC,
    DEFAULT_SEGMENT_COUNT,
    GALACTIC_CENTRE_DEC_DEG,
    GALACTIC_CENTRE_RA_DEG,
    GALACTIC_POLE_DEC_DEG,
    GALACTIC_POLE_RA_DEG,
    KIND_DISTANCE_RINGS,
    KIND_ECLIPTIC_PLANE,
    KIND_GALACTIC_PLANE,
    KIND_GRID,
    KIND_ROUTE_CORRIDOR,
    KIND_SECTOR_CONE,
    KIND_WAYPOINT_LABELS,
    MAX_RING_COUNT,
    MAX_SEGMENT_COUNT,
    OBLIQUITY_J2000_DEG,
    OVERLAY_KINDS,
    OverlayBundle,
    OverlayLabel,
    OverlayPolyline,
    OverlaySettings,
    Vec3,
    build_distance_rings,
    build_ecliptic_plane,
    build_galactic_plane,
    build_grid,
    build_overlay_bundle,
    build_route_corridor,
    build_sector_cone,
    build_waypoint_labels,
)

__all__ = [
    "BoundingSphere",
    "DEFAULT_OVERLAY_RADIUS_PC",
    "DEFAULT_SEGMENT_COUNT",
    "DEFAULT_SHELL_REDSHIFTS",
    "DensityHeatmap",
    "GALACTIC_CENTRE_DEC_DEG",
    "GALACTIC_CENTRE_RA_DEG",
    "GALACTIC_POLE_DEC_DEG",
    "GALACTIC_POLE_RA_DEG",
    "HUBBLE_KM_S_MPC",
    "KIND_DISTANCE_RINGS",
    "KIND_ECLIPTIC_PLANE",
    "KIND_GALACTIC_PLANE",
    "KIND_GRID",
    "KIND_ROUTE_CORRIDOR",
    "KIND_SECTOR_CONE",
    "KIND_WAYPOINT_LABELS",
    "MAX_RING_COUNT",
    "MAX_SEGMENT_COUNT",
    "OBLIQUITY_J2000_DEG",
    "OVERLAY_KINDS",
    "OverlayBundle",
    "OverlayLabel",
    "OverlayPolyline",
    "OverlaySettings",
    "RedshiftShells",
    "SPEED_OF_LIGHT_KM_S",
    "SourceDistribution",
    "Vec3",
    "build_distance_rings",
    "build_ecliptic_plane",
    "build_galactic_plane",
    "build_grid",
    "build_overlay_bundle",
    "build_route_corridor",
    "build_sector_cone",
    "build_waypoint_labels",
    "compute_bounding_sphere",
    "compute_density_heatmap_placeholder",
    "compute_redshift_shells_placeholder",
    "compute_source_distribution",
]
